<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-9QCAOA2C" failures="1" tests="3" name="Surefire test" time="8.384" errors="0" timestamp="2025-08-31T17:58:31 CDT">
  <testcase classname="com.checkers.tests.CheckersTest" name="testSiteIsUp" time="2.267"/>
  <testcase classname="com.checkers.tests.CheckersTest" name="testMakeFiveMovesIncludingCapture" time="3.178">
    <failure type="java.lang.AssertionError" message="Exactly 5 moves should be made. expected [5] but found [0]">
      <![CDATA[java.lang.AssertionError: Exactly 5 moves should be made. expected [5] but found [0]
at com.checkers.tests.CheckersTest.testMakeFiveMovesIncludingCapture(CheckersTest.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testMakeFiveMovesIncludingCapture -->
  <testcase classname="com.checkers.tests.CheckersTest" name="testRestartGame" time="0.904"/>
</testsuite> <!-- Surefire test -->
