<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-31T17:58:22 CDT" name="Surefire suite" finished-at="2025-08-31T17:58:31 CDT" duration-ms="8384">
    <groups>
    </groups>
    <test started-at="2025-08-31T17:58:22 CDT" name="Surefire test" finished-at="2025-08-31T17:58:31 CDT" duration-ms="8384">
      <class name="com.checkers.tests.CheckersTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.checkers.tests.CheckersTest@3c419631]" started-at="2025-08-31T17:58:22 CDT" name="setup" finished-at="2025-08-31T17:58:24 CDT" duration-ms="1612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testSiteIsUp()[pri:1, instance:com.checkers.tests.CheckersTest@3c419631]" started-at="2025-08-31T17:58:24 CDT" name="testSiteIsUp" finished-at="2025-08-31T17:58:26 CDT" duration-ms="2267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSiteIsUp -->
        <test-method signature="testMakeFiveMovesIncludingCapture()[pri:2, instance:com.checkers.tests.CheckersTest@3c419631]" started-at="2025-08-31T17:58:26 CDT" name="testMakeFiveMovesIncludingCapture" finished-at="2025-08-31T17:58:29 CDT" duration-ms="3178" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Exactly 5 moves should be made. expected [5] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Exactly 5 moves should be made. expected [5] but found [0]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at com.checkers.tests.CheckersTest.testMakeFiveMovesIncludingCapture(CheckersTest.java:103)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMakeFiveMovesIncludingCapture -->
        <test-method signature="testRestartGame()[pri:3, instance:com.checkers.tests.CheckersTest@3c419631]" started-at="2025-08-31T17:58:29 CDT" name="testRestartGame" finished-at="2025-08-31T17:58:30 CDT" duration-ms="904" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRestartGame -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.checkers.tests.CheckersTest@3c419631]" started-at="2025-08-31T17:58:30 CDT" name="tearDown" finished-at="2025-08-31T17:58:31 CDT" duration-ms="374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.checkers.tests.CheckersTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
